# Generated by Django 2.2.3 on 2019-07-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registr',
            name='password',
        ),
    ]
