# Generated by Django 2.2.3 on 2019-07-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_registr_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registr',
            name='image1',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='pic_folder/'),
        ),
    ]
