# Generated by Django 2.2.4 on 2019-08-01 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190717_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBrowser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='registr',
            name='browser',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registr',
            name='image1',
            field=models.ImageField(default='', upload_to='thumbnails/image/'),
        ),
    ]
