# Generated by Django 2.2.4 on 2019-08-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190801_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registr',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='registr',
            name='image1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='thumbnails/image/'),
        ),
    ]
